### ISSUE TITLE
Repetition in codebase.md

### ISSUE THREAD

**Issue by iamprakashom** [OfflineIMAP/imapfw-documentation#2]
In `codebase.md`, [Line 85](https://github.com/OfflineIMAP/imapfw-documentation/blame/master/developers/codebase.md#L85) to [Line 101](https://github.com/OfflineIMAP/imapfw-documentation/blame/master/developers/codebase.md#L101) is repeating at the end.

**Comment by nicolas33** [comment]
Please fork, fix and PR. :-)

**Comment by iamprakashom** [comment]
PR is almost ready. wait a moment. :smile:

**Comment by iamprakashom** [comment]
PR #3 sent.

**Comment by iamprakashom** [comment]
This is also causing git book to display redundant info on [this page](http://imapfwdoc.offlineimap.org/developers/codebase.html).

**Comment by nicolas33** [comment]
Notice that the book online is _directly_ built from this repository. Hence, any change made here automatically updates the book online. :-)
